# Generated by Django 4.0.3 on 2022-03-24 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='bmiapi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Gender', models.CharField(max_length=256, unique=True)),
                ('HeightCm', models.FloatField()),
                ('WeightKg', models.FloatField()),
                ('bmi', models.FloatField()),
            ],
        ),
    ]
