# Generated by Django 4.0.3 on 2022-03-25 11:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bmi', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bmiapi',
            name='bmi',
        ),
    ]
